# Generated by Django 3.0.3 on 2020-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, verbose_name='host category')),
                ('hostname', models.CharField(max_length=50, verbose_name='host name')),
                ('port', models.IntegerField(default=22, verbose_name='host port')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'host',
                'db_table': 'hosts',
                'ordering': ('-id', ),
            },
        ),
    ]
