# Generated by Django 3.0.3 on 2020-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='docker_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='docker port'),
        ),
    ]
