# Generated by Django 3.0.3 on 2020-03-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200309_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Menu')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('ALL', 'ALL')], max_length=10, verbose_name='HTTP method')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permission',
            },
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created',), 'verbose_name': 'token', 'verbose_name_plural': 'token'},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('status', models.BooleanField(default=True)),
                ('menus', models.ManyToManyField(to='account.Menu', verbose_name='role menu')),
                ('permissions', models.ManyToManyField(blank=True, to='account.Permission', verbose_name='role permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='account.Role', verbose_name='user roles'),
        ),
    ]
