# Generated by Django 3.0.3 on 2020-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200313_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='account.Menu', verbose_name='role menu'),
        ),
    ]
